apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valkyrie.fullname" . }}
  labels:
    {{- include "valkyrie.labels" . | nindent 4 }}
data:
  valkyrie_config.yml: |-
    {{- toYaml .Values.config | nindent 4}}
  {{- if .Values.otel.enabled }}
  collector.yaml: |-
    {{- required "otel-collector configuration has to be provided in .Values.otel.config" .Values.otel.config | toYaml | nindent 4 }}
  {{- end }}
