apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valkyrie.fullname" . }}
  labels:
    {{- include "valkyrie.labels" . | nindent 4 }}
data:
  valkyrie_config.yml: |-
    {{- toYaml .Values.config | nindent 4}}
