apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkyrie.fullname" . }}-operator
  labels:
    {{- include "valkyrie.labels" . | nindent 4 }}
  {{- with .Values.operatorService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.operatorService.type }}
  ports:
    - port: {{ .Values.operatorService.port }}
      targetPort: httpclient-operator
      protocol: TCP
      name: httpclient-operator
  selector:
    {{- include "valkyrie.selectorLabels" . | nindent 4 }}
