package example

import (
	"github.com/gofiber/fiber/v2"
)

// Controller use for setting up the wallet endpoint functions. Here request and header validation can be done.
// If you're using oapi-codegen, this part can be autogenerated.
// This is just an example of how the controller could be set up using generics.
type Controller struct {
	walletService *WalletService
}

func NewController(walletService *WalletService) *Controller {
	return &Controller{walletService: walletService}
}

type requestType interface {
	balanceRequest | authRequest | betRequest | winRequest // Add all request types the provider supports
}

// execController generic function parsing and handling all request parsing and validation that is the same for all wallet requests.
func execController[T requestType](c *fiber.Ctx, svcFunc func(req T) (any, error)) error {
	var req T

	// Parse request. In this example it is using bodyParser. If the wallet pass data in some other way that can be dealt with here.
	if err := c.BodyParser(&req); err != nil {
		// Handle errors as expected by the game provider wallet api.
		return c.Status(fiber.StatusBadRequest).JSON(err)
	}

	// Call the walletService
	resp, err := svcFunc(req)
	// If error, return it
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(errorResponse{Err: err.Error()})
	}
	return c.Status(fiber.StatusOK).JSON(resp)
}

func (c *Controller) Balance(ctx *fiber.Ctx) error {
	return execController(ctx, func(r balanceRequest) (any, error) {
		// walletService handles the mapping toward the Valkyrie pam api, pam.PamClient.
		balance, err := c.walletService.GetBalance(ctx.UserContext(), r)
		if err != nil {
			return nil, err
		}

		// return what provider wallet api needs
		return balanceResponse{Balance: balance.CashAmount}, nil
	})
}

func (c *Controller) Auth(ctx *fiber.Ctx) error {
	return execController(ctx, func(r authRequest) (any, error) {
		session, err := c.walletService.Auth(ctx.UserContext(), r)
		if err != nil {
			return nil, err
		}

		return authResponse{Token: session.Token}, nil
	})
}

func (c *Controller) Bet(ctx *fiber.Ctx) error {
	return execController(ctx, func(r betRequest) (any, error) {
		balance, err := c.walletService.Bet(ctx.UserContext(), r)
		if err != nil {
			return nil, err
		}

		return betResponse{Balance: balance.CashAmount}, nil
	})
}

func (c *Controller) Win(ctx *fiber.Ctx) error {
	return execController(ctx, func(r winRequest) (any, error) {
		balance, err := c.walletService.Win(ctx.UserContext(), r)
		if err != nil {
			return nil, err
		}

		return winResponse{Balance: balance.CashAmount}, nil
	})
}
