openapi: 3.0.0 # swagger doesn't support >= 3.1.0 yet unfortunately
info:
  title: Valkyrie Operator API
  description: |
    Valkyrie endpoints for communicating with a provider. Exposed valkyrie endpoints can differ between configured provider modules. Make sure the ones you want to use are implemented.
  version: 0.2.0
  license:
    name: MIT
    url: https://github.com/valkyrie-fnd/valkyrie/blob/main/LICENSE.md
servers:
  - url: http://localhost:8084
    description: operator server
paths:
  /{provider}/gamelaunch:
    post:
      description: Launch a provider game through valkyrie
      operationId: GameLaunch
      summary: Launch game
      parameters:
        - in: path
          name: provider
          required: true
          description: Provider identification string. Depending on configured Valkyrie
          example: redtiger
          schema:
            type: string
        - $ref: "#/components/parameters/sessionToken"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/gameLaunchRequest"

      responses:
        "200":
          description: Successfully launched the specified provider game
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/gameLaunchResponse"

        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: string
              example: Bad game launch call
  /{provider}/gamerounds/{gameRoundId}/render:
    get:
      description: Optional. Returns a rendered representation of the specified game round.
      operationId: GameRoundRender
      summary: Render game round
      parameters:
        - in: path
          name: provider
          required: true
          description: Provider identification string. Depending on configured Valkyrie.
          example: caleta
          schema:
            type: string
        - in: path
          name: gameRoundId
          required: true
          description: id of gameround to rendered
          example: xyz123
          schema:
            type: string
      responses:
        "302":
          description: Redirect to provider specific url with rendered result
        "500":
          description: Something went wrong fetching the rendered page
components:
  parameters:
    sessionToken:
      name: X-Player-Token
      description: Player game session identifier
      in: header
      required: true
      schema:
        $ref: "#/components/schemas/sessionToken"
  schemas:
    gameLaunchRequest:
      type: object
      required:
        - currency
        - providerGameId
        - playerId
      properties:
        casino:
          type: string
          example: YourCasino
        country:
          type: string
          example: SE
        currency:
          type: string
          example: SEK
        providerGameId:
          type: string
          example: BadLuck
        language:
          type: string
          example: sv
        launchConfig:
          $ref: "#/components/schemas/launchConfig"
        playerId:
          type: string
          example: Tyrone
        sessionIp:
          type: string
          example: 0.0.0.0
    gameLaunchResponse:
      type: object
      properties:
        gameUrl:
          type: string
    launchConfig:
      type: object
      example: '{"providerSpecificConfiguration": "Value", "brandId": 1}'
    sessionToken:
      description: Player game session identifier
      type: string
      example: 7ca10daf12f2cac9fecf559b11f0f0c8bd21ae43
      minLength: 1
      maxLength: 40
