name: CI

on:
  pull_request:
  push:
    tags:
      - "v*.*.*"
      - "!v*.*.*-*" # filter out prerelease tags
    branches:
      - main
jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 3m

  Test:
    name: Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Run tests
        run: |
          set -euo pipefail
          go install gotest.tools/gotestsum@latest
          gotestsum -- -coverprofile coverage.out -covermode=count ./...
      - uses: seriousben/go-patch-cover-action@v1
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}

  Push:
    name: Push container and chart to registry
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    needs: [Lint, Test]
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      DOCKER_REPO: docker.io/valkyriefnd
      HELM_REPO: docker.io/valkyriefnd/
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all revision and tags, necessary for .github/tools/version.sh
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Build and push Docker image to registry
        run: |-
          task docker-push
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - name: Push chart to registry
        run: |
          task helm-push


# Credits to https://alexejk.io/article/building-releasing-github-actions/ that inspired this.
#
# To trigger a release, make sure a corresponding version entry (X.X.X) has been added to CHANGELOG.md.
# Then push a git tag in the format "vX.X.X" to trigger the release workflow.
  Release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ Lint, Test ]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Build release
        run: |
          task package-all
      - name: Generate Changelog
        run: |
          task changelog > build/GEN-CHANGELOG.md
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          body_path: build/GEN-CHANGELOG.md
          files: |
            build/*.tar.gz
            build/*.zip
