name: Notify discord

on:
  pull_request:
    types: [review_requested]

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "{{ EVENT_PAYLOAD.pull_request.user.login }} wants **${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }}** to review PR: `{{ EVENT_PAYLOAD.pull_request.title }}` <{{ EVENT_PAYLOAD.pull_request.html_url }}>"
