name: Release
run-name: Release v${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: |
          Specify the version to release.
          The version should be in `X.X.X`-format, following semver.
        required: true

jobs:
  CI:
    uses: ./.github/workflows/gh-workflow.yml
    with:
      version: ${{ inputs.version }}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  Release:
    runs-on: ubuntu-latest
    needs: [CI]
    env:
      VERSION: ${{ inputs.version }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Build release
        run: |
          task package:all
      - name: Generate Changelog
        run: |
          task changelog > build/GEN-CHANGELOG.md
      - name: Tag release version
        run: |
          git tag v${{ inputs.version }}
          git push origin v${{ inputs.version }}
      - name: Publish release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          body_path: build/GEN-CHANGELOG.md
          tag_name: v${{ inputs.version }}
          files: |
            build/*.tar.gz
            build/*.zip
